name: Build Repo Listing

on: 
  workflow_dispatch:
  push:
    branches: main
    paths: input.json

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  
# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true
  
env:
  listPublishDirectory: Website
  pathToCi: ci

jobs:
  build-listing:
    name: build-listing
    uses: hai-vr/pristine-listing-action/.github/workflows/build-and-publish.yml@main
    permissions:
      contents: write
      pages: write
      id-token: write
    with:
      includeDownloadCount: true
      devonly: true
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
